# coding: utf-8

"""
    Flashcards API

    API Docs for flashcards-server  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""

from flashcards_api_client.paths.decks_deck_id_cards_card_id_related.put import AddRelatedCardToCard
from flashcards_api_client.paths.decks_deck_id_cards_card_id_context_answer_fact_id.put import AssignAnswerContextToCard
from flashcards_api_client.paths.decks_deck_id_cards_card_id_context_question_fact_id.put import AssignQuestionContextToCard
from flashcards_api_client.paths.decks_deck_id_cards_card_id_tags_tag_name.put import AssignTagToCard
from flashcards_api_client.paths.decks_deck_id_cards.post import CreateCard
from flashcards_api_client.paths.decks_.post import CreateDeck
from flashcards_api_client.paths.decks_deck_id_cards_card_id.delete import DeleteCard
from flashcards_api_client.paths.decks_deck_id.delete import DeleteDeck
from flashcards_api_client.paths.decks_deck_id_cards_card_id.patch import EditCard
from flashcards_api_client.paths.decks_deck_id.patch import EditDeck
from flashcards_api_client.paths.decks_deck_id_cards_card_id.get import GetCard
from flashcards_api_client.paths.decks_deck_id_cards.get import GetCards
from flashcards_api_client.paths.decks_deck_id.get import GetDeck
from flashcards_api_client.paths.decks.get import GetMyDecks
from flashcards_api_client.paths.decks_deck_id_cards_card_id_reviews.get import GetReviews
from flashcards_api_client.paths.decks_deck_id_cards_card_id_context_answer_fact_id.delete import RemoveAnswerContextFromCard
from flashcards_api_client.paths.decks_deck_id_cards_card_id_context_question_fact_id.delete import RemoveQuestionContextFromCard
from flashcards_api_client.paths.decks_deck_id_cards_card_id_related.delete import RemoveRelatedCard
from flashcards_api_client.paths.decks_deck_id_cards_card_id_tags_tag_name.delete import RemoveTagFromCard


class DecksApi(
    AddRelatedCardToCard,
    AssignAnswerContextToCard,
    AssignQuestionContextToCard,
    AssignTagToCard,
    CreateCard,
    CreateDeck,
    DeleteCard,
    DeleteDeck,
    EditCard,
    EditDeck,
    GetCard,
    GetCards,
    GetDeck,
    GetMyDecks,
    GetReviews,
    RemoveAnswerContextFromCard,
    RemoveQuestionContextFromCard,
    RemoveRelatedCard,
    RemoveTagFromCard,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
