# coding: utf-8

"""
    Flashcards API

    API Docs for flashcards-server  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""

from flashcards_api_client.paths.facts_fact_id_related_.put import AssignRelatedFact
from flashcards_api_client.paths.facts_fact_id_tags_tag_name.put import AssignTagToFact
from flashcards_api_client.paths.facts_.post import CreateFact
from flashcards_api_client.paths.facts_fact_id.delete import DeleteFact
from flashcards_api_client.paths.facts_fact_id.patch import EditFact
from flashcards_api_client.paths.facts_fact_id.get import GetFact
from flashcards_api_client.paths.facts_.get import GetFacts
from flashcards_api_client.paths.facts_tag_tag_name.get import GetFactsByTag
from flashcards_api_client.paths.facts_fact_id_related_.delete import RemoveRelatedFact
from flashcards_api_client.paths.facts_fact_id_tags_tag_name.delete import RemoveTagFromFact


class FactsApi(
    AssignRelatedFact,
    AssignTagToFact,
    CreateFact,
    DeleteFact,
    EditFact,
    GetFact,
    GetFacts,
    GetFactsByTag,
    RemoveRelatedFact,
    RemoveTagFromFact,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
