# coding: utf-8

"""
    Flashcards API

    API Docs for flashcards-server  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""

from flashcards_api_client.paths.users_me.get import UsersCurrentUser
from flashcards_api_client.paths.users_id.delete import UsersDeleteUser
from flashcards_api_client.paths.users_me.patch import UsersPatchCurrentUser
from flashcards_api_client.paths.users_id.patch import UsersPatchUser
from flashcards_api_client.paths.users_id.get import UsersUser


class UsersApi(
    UsersCurrentUser,
    UsersDeleteUser,
    UsersPatchCurrentUser,
    UsersPatchUser,
    UsersUser,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
