# coding: utf-8

"""
    Flashcards API

    API Docs for flashcards-server  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""

import unittest

import flashcards_api_client
from flashcards_api_client.model.error_model import ErrorModel
from flashcards_api_client import configuration


class TestErrorModel(unittest.TestCase):
    """ErrorModel unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
