# coding: utf-8

"""
    Flashcards API

    API Docs for flashcards-server  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""

import unittest

import flashcards-api-client
from flashcards-api-client.model.body_verify_request_token_request_verify_token_post import BodyVerifyRequestTokenRequestVerifyTokenPost
from flashcards-api-client import configuration


class TestBodyVerifyRequestTokenRequestVerifyTokenPost(unittest.TestCase):
    """BodyVerifyRequestTokenRequestVerifyTokenPost unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
