# coding: utf-8

"""
    Flashcards API

    API Docs for flashcards-server  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""

import unittest

import flashcards-api-client
from flashcards-api-client.model.body_reset_forgot_password_forgot_password_post import BodyResetForgotPasswordForgotPasswordPost
from flashcards-api-client import configuration


class TestBodyResetForgotPasswordForgotPasswordPost(unittest.TestCase):
    """BodyResetForgotPasswordForgotPasswordPost unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
