# coding: utf-8

"""
    Flashcards API

    API Docs for flashcards-server  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""

from flashcards-api-client.paths.auth_jwt_login.post import AuthJwtLogin
from flashcards-api-client.paths.auth_jwt_logout.post import AuthJwtLogout
from flashcards-api-client.paths.register.post import RegisterRegister
from flashcards-api-client.paths.forgot_password.post import ResetForgotPassword
from flashcards-api-client.paths.reset_password.post import ResetResetPassword
from flashcards-api-client.paths.request_verify_token.post import VerifyRequestToken
from flashcards-api-client.paths.verify.post import VerifyVerify


class AuthApi(
    AuthJwtLogin,
    AuthJwtLogout,
    RegisterRegister,
    ResetForgotPassword,
    ResetResetPassword,
    VerifyRequestToken,
    VerifyVerify,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
