# coding: utf-8

"""
    Flashcards API

    API Docs for flashcards-server  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""

from flashcards-api-client.paths.study_deck_id_start.get import FirstCard
from flashcards-api-client.paths.study_deck_id_next.post import NextCard


class StudyApi(
    FirstCard,
    NextCard,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
