# coding: utf-8

# flake8: noqa

"""
    Flashcards API

    API Docs for flashcards-server  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from flashcards-api-client.api_client import ApiClient

# import Configuration
from flashcards-api-client.configuration import Configuration

# import exceptions
from flashcards-api-client.exceptions import OpenApiException
from flashcards-api-client.exceptions import ApiAttributeError
from flashcards-api-client.exceptions import ApiTypeError
from flashcards-api-client.exceptions import ApiValueError
from flashcards-api-client.exceptions import ApiKeyError
from flashcards-api-client.exceptions import ApiException
