# coding: utf-8

# flake8: noqa

"""
    Flashcards API

    API Docs for flashcards-server  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from flashcards_api_client.api_client import ApiClient

# import Configuration
from flashcards_api_client.configuration import Configuration

# import exceptions
from flashcards_api_client.exceptions import OpenApiException
from flashcards_api_client.exceptions import ApiAttributeError
from flashcards_api_client.exceptions import ApiTypeError
from flashcards_api_client.exceptions import ApiValueError
from flashcards_api_client.exceptions import ApiKeyError
from flashcards_api_client.exceptions import ApiException
